version: '3'
services:
  frp_client:
    image: geektr/frp
    restart: always
    env_file:
      - "$secrets_dir/frp/frp.env"
    volumes:
      - "$service_dir/conf/frp/frpc.ini:/etc/frp/frpc.ini:ro"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE=jumpserver
      MYSQL_ROOT_PASSWORD=password
    volumes: 
     - "$data_dir/mysql:/var/lib/mysql"
     - "$service_dir/conf/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
  jumpserver:
    image: wojiushixiaobai/jumpserver
    restart: always
    environment: 
      DB_ENGINE=mysql
      DB_HOST=mysql
      DB_PORT=3306
      DB_USER=root
      DB_PASSWORD=password
      DB_NAME=jumpserver
    ports:
      - '$acl_ip:22:2222'
      - '$acl_ip:80:80'
    volumes:
      - '$data_dir/jumpserver:/opt/jumpserver/data'
      - '$data_dir/coco:/opt/coco/keys'
      - '$data_dir/guacamole:/config/guacamole/keys'
